version: '3.2'

services:
  
  bitcoind:
    image: registry.gitlab.com/hashbeam/docker/bitcoind:23.0
    command: "-fallbackfee=0.0002"
    volumes:
      - ./data/bitcoin:/srv/app/.bitcoin
  electrs:
    image: registry.gitlab.com/hashbeam/docker/electrs:0.9.9
    volumes:
      - ./data/electrs:/srv/app/db
    depends_on:
      - bitcoind
  jupyter:
    image: rgb-lib-python-demo
    build: .
    ports:
      - 8888:8888
    depends_on:
      - electrs