version: '3.7'

services:
  bitcoind:
    image: registry.gitlab.com/hashbeam/docker/bitcoind:25.0
    command: "-fallbackfee=0.0002"
    volumes:
      - ./data/bitcoin:/srv/app/.bitcoin
  electrs:
    image: registry.gitlab.com/hashbeam/docker/electrs:0.9.14
    ports:
      - 50001:50001
    volumes:
      - ./data/electrs:/srv/app/db
    depends_on:
      - bitcoind
  proxy:
    image: ghcr.io/grunch/rgb-proxy-server:0.2.0
    ports:
      - 3000:3000
  minter:
    build:
      context: .
      dockerfile: Dockerfile
    restart:
      always
    ports:
      - 8000:8000
      - 8501:8501
    volumes: 
      -  ./:/app
    depends_on:
      - proxy
      - electrs
      - bitcoind
